# Generated by Django 3.1.7 on 2021-04-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date registered')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField(verbose_name='Total amount')),
                ('date', models.DateField(verbose_name='Date of purchase')),
            ],
            options={
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service name')),
                ('amount', models.PositiveIntegerField(verbose_name='Service amount')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date registered')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceOffered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Total amount')),
                ('date', models.DateField(verbose_name='Date of purchase')),
                ('payment', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mjapp.customers', verbose_name='Customers name')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mjapp.services', verbose_name='Service offered')),
            ],
            options={
                'verbose_name_plural': 'Services done',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of service')),
                ('status', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mjapp.customers')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
