# Generated by Django 3.1.7 on 2021-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='amount',
            field=models.CharField(max_length=500, verbose_name='Service amount range'),
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
