# Generated by Django 3.1.7 on 2021-04-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjapp', '0002_auto_20210405_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='payed'),
        ),
    ]
