# Generated by Django 3.1.6 on 2021-04-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjapp', '0003_auto_20210406_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffered',
            name='date',
            field=models.DateField(verbose_name='Date of delivery'),
        ),
        migrations.AlterField(
            model_name='serviceoffered',
            name='service',
            field=models.ForeignKey(default='Service name deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='mjapp.services', verbose_name='Service offered'),
        ),
    ]
